"""
SYS-5: auto_implement_gap handler — implementa gaps aprovados pelo Mauro.

Gap type handling:
- knowledge: Auto-triggers brain_ingest_pipeline with a search query generated by Haiku.
- capability: Flags for @architect review via activate_agent task.
- handler: Generates a basic handler template via Haiku, saves to pending review.
- agent: Generates agent definition via Haiku, saves to pending review.

Status tracking: updates gap_reports.status and gap_reports.implementation_result
throughout the lifecycle (implementing -> implemented | implementation_failed).
"""
from __future__ import annotations

import asyncio
import json
import traceback
from datetime import datetime, timezone

from runtime.config import settings
from runtime.db import supabase
from runtime.utils.llm import call_claude


# ── Helpers ──────────────────────────────────────────────────


async def _get_gap(gap_id: str) -> dict | None:
    try:
        result = await asyncio.to_thread(
            lambda: supabase.table("gap_reports")
            .select("*")
            .eq("id", gap_id)
            .single()
            .execute()
        )
        return result.data
    except Exception:
        return None


async def _update_gap_status(
    gap_id: str,
    status: str,
    *,
    resolution: str = "",
    implementation_result: dict | None = None,
) -> None:
    update_data: dict = {
        "status": status,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    if resolution:
        update_data["resolution"] = resolution
    if implementation_result is not None:
        update_data["implementation_result"] = implementation_result
    await asyncio.to_thread(
        lambda: supabase.table("gap_reports")
        .update(update_data)
        .eq("id", gap_id)
        .execute()
    )


async def _create_runtime_task(
    agent_id: str,
    task_type: str,
    payload: dict,
    priority: int = 6,
) -> dict:
    result = await asyncio.to_thread(
        lambda: supabase.table("runtime_tasks").insert({
            "agent_id": agent_id,
            "client_id": settings.sparkle_internal_client_id,
            "task_type": task_type,
            "payload": payload,
            "status": "pending",
            "priority": priority,
        }).execute()
    )
    return result.data[0] if result.data else {}


def _parse_json_response(raw: str) -> dict | None:
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        lines = [l for l in lines if not l.strip().startswith("```")]
        cleaned = "\n".join(lines).strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        return None


# ── Knowledge Gap: auto-resolve via brain ingest ─────────────


_SEARCH_QUERY_SYSTEM = """Voce recebera a descricao de um gap de conhecimento detectado pelo Observer da Sparkle AIOX.
Gere UMA query de busca curta (maximo 10 palavras) em portugues para pesquisar sobre o tema.
A query deve ser especifica e acionavel para encontrar informacao pratica.

Responda APENAS com JSON: {"search_query": "sua query aqui", "topic": "tema resumido em 3 palavras"}"""


async def _handle_knowledge_gap(gap: dict) -> dict:
    """
    Knowledge gaps auto-resolve:
    1. Use Haiku to generate a search query from the gap description
    2. Create a brain_ingest_pipeline task with the topic for ingestion
    """
    summary = gap.get("summary", "")
    details = gap.get("details", {})
    description = f"Gap: {summary}. Detalhes: {json.dumps(details, ensure_ascii=False)}"

    # Generate search query via Haiku
    raw = await call_claude(
        prompt=description,
        system=_SEARCH_QUERY_SYSTEM,
        model="claude-haiku-4-5-20251001",
        client_id=settings.sparkle_internal_client_id,
        agent_id="observer",
        purpose="gap_search_query_generation",
        max_tokens=128,
    )

    parsed = _parse_json_response(raw)
    search_query = parsed.get("search_query", summary[:80]) if parsed else summary[:80]
    topic = parsed.get("topic", summary[:40]) if parsed else summary[:40]

    # Create brain_ingest_pipeline task with the topic as content to ingest
    task = await _create_runtime_task(
        agent_id="observer",
        task_type="brain_ingest_pipeline",
        payload={
            "raw_content": (
                f"Pesquisa automatica sobre: {search_query}\n\n"
                f"Contexto do gap detectado: {summary}\n"
                f"Detalhes: {json.dumps(details, ensure_ascii=False)}\n\n"
                f"Este conteudo foi gerado automaticamente pelo Observer para preencher "
                f"uma lacuna de conhecimento no Brain da Sparkle AIOX."
            ),
            "source_type": "direct_input",
            "title": f"Observer auto-ingest: {topic}",
            "persona": "especialista",
            "run_dna": False,
            "run_insights": True,
            "run_narrative": False,
            "run_synthesis": False,
            "auto_generated": True,
            "gap_id": gap.get("id"),
        },
        priority=6,
    )

    return {
        "action": "knowledge_auto_ingested",
        "search_query": search_query,
        "topic": topic,
        "ingest_task_id": task.get("id"),
        "note": "Brain ingest pipeline criada automaticamente para preencher gap de conhecimento.",
    }


# ── Capability Gap: flag for @architect review ───────────────


async def _handle_capability_gap(gap: dict) -> dict:
    """
    Capability gaps require human review.
    Creates an activate_agent task targeting @architect to design the capability.
    """
    summary = gap.get("summary", "")
    details = gap.get("details", {})

    task = await _create_runtime_task(
        agent_id="system",
        task_type="activate_agent",
        payload={
            "agent": "@architect",
            "request": (
                f"O Observer detectou um gap de capacidade no sistema: {summary}. "
                f"Detalhes: {json.dumps(details, ensure_ascii=False)}. "
                f"Por favor, analise e projete a solucao para essa capacidade faltante. "
                f"Documente a decisao arquitetural e os passos de implementacao."
            ),
            "source": "observer_auto_implement",
            "gap_id": gap.get("id"),
        },
        priority=5,
    )

    return {
        "action": "capability_flagged_for_review",
        "assigned_to": "@architect",
        "task_id": task.get("id"),
        "note": "Gap de capacidade requer design arquitetural. Task criada para @architect.",
    }


# ── Handler Gap: generate template, flag for @dev review ─────


_HANDLER_TEMPLATE_SYSTEM = """Voce e um desenvolvedor Python senior da Sparkle AIOX.
Gere um template basico de handler para o runtime da Sparkle.

O handler deve seguir este padrao:
- Funcao async chamada handle_<nome>(task: dict) -> dict
- Recebe task com payload, retorna dict com resultado
- Inclua docstring explicando o proposito
- Inclua tratamento de erro basico
- Use imports de runtime.config, runtime.db se necessario

Responda APENAS com JSON:
{
  "handler_name": "nome_do_handler",
  "file_name": "nome_do_handler.py",
  "code": "codigo python completo do handler",
  "description": "descricao curta do que faz",
  "task_type": "o task_type que este handler atende"
}"""


async def _handle_handler_gap(gap: dict) -> dict:
    """
    Handler gaps: generate a basic template via Haiku, save to gap details for @dev review.
    """
    summary = gap.get("summary", "")
    details = gap.get("details", {})

    raw = await call_claude(
        prompt=(
            f"Crie um handler para: {summary}\n"
            f"Detalhes do gap: {json.dumps(details, ensure_ascii=False)}"
        ),
        system=_HANDLER_TEMPLATE_SYSTEM,
        model="claude-haiku-4-5-20251001",
        client_id=settings.sparkle_internal_client_id,
        agent_id="observer",
        purpose="gap_handler_template_generation",
        max_tokens=1024,
    )

    parsed = _parse_json_response(raw)
    if not parsed:
        parsed = {
            "handler_name": "unknown",
            "file_name": "unknown.py",
            "code": "# Haiku failed to generate template",
            "description": summary,
            "task_type": "unknown",
        }

    # Create task for @dev to review and implement
    task = await _create_runtime_task(
        agent_id="system",
        task_type="activate_agent",
        payload={
            "agent": "@dev",
            "request": (
                f"O Observer detectou que falta um handler no runtime: {summary}. "
                f"Um template foi gerado automaticamente (ver implementation_result do gap). "
                f"Revise o template, ajuste conforme necessario e registre no registry.py. "
                f"Handler sugerido: {parsed.get('handler_name', 'unknown')}"
            ),
            "source": "observer_auto_implement",
            "gap_id": gap.get("id"),
            "handler_template": parsed,
        },
        priority=5,
    )

    return {
        "action": "handler_template_generated",
        "assigned_to": "@dev",
        "task_id": task.get("id"),
        "handler_template": parsed,
        "note": "Template de handler gerado por Haiku. Requer revisao do @dev antes de ativar.",
    }


# ── Agent Gap: generate agent definition, flag for review ────


_AGENT_DEFINITION_SYSTEM = """Voce e o arquiteto de agentes da Sparkle AIOX.
Gere uma definicao basica de agente para o runtime.

O agente deve incluir:
- Nome e papel claro
- System prompt com instrucoes de comportamento
- Lista de ferramentas que o agente precisa
- Regras de operacao

Responda APENAS com JSON:
{
  "agent_key": "nome_curto_sem_espacos",
  "display_name": "Nome Exibicao",
  "role": "descricao do papel em 1 frase",
  "system_prompt": "prompt completo do agente",
  "tools": ["brain_query", "supabase_read"],
  "rules": ["regra 1", "regra 2"]
}"""


async def _handle_agent_gap(gap: dict) -> dict:
    """
    Agent gaps: generate agent definition via Haiku, save for review.
    Creates a context block but does NOT auto-activate.
    """
    summary = gap.get("summary", "")
    details = gap.get("details", {})

    raw = await call_claude(
        prompt=(
            f"Crie uma definicao de agente para: {summary}\n"
            f"Detalhes do gap: {json.dumps(details, ensure_ascii=False)}"
        ),
        system=_AGENT_DEFINITION_SYSTEM,
        model="claude-haiku-4-5-20251001",
        client_id=settings.sparkle_internal_client_id,
        agent_id="observer",
        purpose="gap_agent_definition_generation",
        max_tokens=1024,
    )

    parsed = _parse_json_response(raw)
    if not parsed:
        parsed = {
            "agent_key": "unknown",
            "display_name": "Unknown Agent",
            "role": summary,
            "system_prompt": f"Voce e um agente da Sparkle AIOX. Seu papel: {summary}",
            "tools": ["brain_query"],
            "rules": ["Consulte o Brain primeiro"],
        }

    agent_key = parsed.get("agent_key", "unknown")

    # Save context block (inactive by default — requires @dev to activate)
    try:
        await asyncio.to_thread(
            lambda: supabase.table("agent_context_blocks").insert({
                "block_key": f"agent.{agent_key}.bootstrap",
                "layer": "process",
                "agent_id": agent_key,
                "content": parsed.get("system_prompt", ""),
                "priority": 1,
                "active": False,  # Inactive until reviewed
            }).execute()
        )
    except Exception as e:
        print(f"[auto_implement_gap] falha ao criar context block: {e}")

    # Create task for review
    task = await _create_runtime_task(
        agent_id="system",
        task_type="activate_agent",
        payload={
            "agent": "@dev",
            "request": (
                f"O Observer detectou que falta o agente @{agent_key}: {summary}. "
                f"Uma definicao foi gerada automaticamente (ver implementation_result do gap). "
                f"O context block foi criado INATIVO. Revise, ajuste e ative quando pronto. "
                f"Para ativar: setar active=true em agent_context_blocks e adicionar em _AVAILABLE_AGENTS."
            ),
            "source": "observer_auto_implement",
            "gap_id": gap.get("id"),
            "agent_definition": parsed,
        },
        priority=5,
    )

    return {
        "action": "agent_definition_generated",
        "assigned_to": "@dev",
        "task_id": task.get("id"),
        "agent_key": agent_key,
        "agent_definition": parsed,
        "context_block_created": True,
        "context_block_active": False,
        "note": "Definicao de agente gerada por Haiku. Context block criado INATIVO. Requer revisao do @dev.",
    }


# ── Main Handler ─────────────────────────────────────────────


_GAP_HANDLERS = {
    "knowledge": _handle_knowledge_gap,
    "capability": _handle_capability_gap,
    "handler": _handle_handler_gap,
    "agent": _handle_agent_gap,
}


async def handle_auto_implement_gap(task: dict) -> dict:
    """
    Implementa um gap aprovado pelo Mauro.

    Flow:
    1. Validate gap exists and is approved
    2. Set status to "implementing"
    3. Dispatch to type-specific handler
    4. On success: status = "implemented" + implementation_result
    5. On failure: status = "implementation_failed" + error
    """
    payload = task.get("payload", {})
    gap_id = payload.get("gap_id")

    if not gap_id:
        return {"error": "gap_id obrigatorio"}

    gap = await _get_gap(gap_id)
    if not gap:
        return {"error": f"Gap {gap_id} nao encontrado"}
    if gap["status"] != "approved":
        return {"error": f"Gap {gap_id} nao esta aprovado (status={gap['status']})"}

    report_type = gap["report_type"]

    # 1. Mark as implementing
    await _update_gap_status(gap_id, "implementing")

    # 2. Dispatch to type-specific handler
    handler = _GAP_HANDLERS.get(report_type)
    if not handler:
        await _update_gap_status(
            gap_id,
            "implementation_failed",
            resolution=f"report_type '{report_type}' nao suportado",
            implementation_result={"error": f"Tipo '{report_type}' sem handler de implementacao"},
        )
        return {"error": f"report_type '{report_type}' nao suportado"}

    try:
        result = await handler(gap)

        # 3. Mark as implemented
        await _update_gap_status(
            gap_id,
            "implemented",
            resolution=result.get("note", str(result.get("action", "implemented"))),
            implementation_result=result,
        )

        return {
            "message": f"Gap {gap_id} implementado ({report_type})",
            "report_type": report_type,
            "result": result,
        }

    except Exception as e:
        error_detail = {
            "error": str(e),
            "traceback": traceback.format_exc()[-500:],
        }
        await _update_gap_status(
            gap_id,
            "implementation_failed",
            resolution=f"Falha: {str(e)[:200]}",
            implementation_result=error_detail,
        )
        return {
            "error": f"Falha ao implementar gap {gap_id}: {e}",
            "report_type": report_type,
        }
